### ISSUE TITLE
line组件的showGrid实际行为是hideGrid

### ISSUE THREAD

**Issue by littleningmeng** [wupeiwen/vue-g2#23]
RT

**Comment by wupeiwen** [comment]
![image](https://user-images.githubusercontent.com/11923878/55323236-1af94880-54b1-11e9-8ed4-ba3d48dd5bd1.png)

**Comment by littleningmeng** [comment]
设计上得写:showGrid="false"才会显示网格线

**Comment by wupeiwen** [comment]
感谢反馈，该缺陷已经在修复中

**Comment by wupeiwen** [comment]
v1.1.2版本已修复该问题
