### ISSUE TITLE
how to set max values in charts

### ISSUE THREAD

**Issue by kabaluyot** [wupeiwen/vue-g2#36]

**Comment by wupeiwen** [comment]
Do you mean axis max value or guide data marker?

**Comment by kabaluyot** [comment]
axis max value sir

**Comment by wupeiwen** [comment]
There is no configuration item for the maximum value of the coordinate axis in the packaged chart. It is recommended to use a custom chart to achieve the requirements.You can refer to the code below.

**Comment by wupeiwen** [comment]
<template>
  <g2-custom :height="380" :data="data" :option="customOption"></g2-custom>
</template>

<script>
// !!!注意: 在vue中使用时需要将"module.exports = {"改为"export default {"
module.exports = {
  name: 'app',
  data () {
    return {
      data: [
        { name: 'test1', value: 123 },
        { name: 'test2', value: 246 }
      ]
    }
  },
  methods: {
    customOption (chart, dataset, data) {
      
      
      chart.source(data,{
       value: {
        tickInterval: 50,
        nice: false,
        max: 250,
        min: 0,
       }
      })
      chart.interval().position('name*value')
    }
  }
}

**Comment by wupeiwen** [comment]
```
<!-- 通过<g2-custom>标签实现简单柱图 -->
<template>
  <g2-custom :height="380" :data="data" :option="customOption"></g2-custom>
</template>

<script>
// !!!注意: 在vue中使用时需要将"module.exports = {"改为"export default {"
module.exports = {
  name: 'app',
  data () {
    return {
      data: [
        { name: 'test1', value: 123 },
        { name: 'test2', value: 246 }
      ]
    }
  },
  methods: {
    customOption (chart, dataset, data) {
      <!-- chart 为图表实例，dataset 为数据集实例， data为图表数据 -->
      
      chart.source(data,{
       value: {
        tickInterval: 50,
        nice: false,
        max: 250,
        min: 0,
       }
      })
      chart.interval().position('name*value')
    }
  }
}
```

**Comment by wupeiwen** [comment]
![image](https://user-images.githubusercontent.com/11923878/75209401-10c2f580-57b9-11ea-986c-09bdc5c8dec4.png)
