### ISSUE TITLE
vue-g2.common.js 中的一个问题 TypeError: Cannot read property 'Chart' of undefined

### ISSUE THREAD

**Issue by kamhung** [wupeiwen/vue-g2#39]
在nuxt.js中使用，vue-g2.common文档中，__webpack_require__ 的getDefault函数会返回@antv/G2模块的default，但@antv/G2模块中没有default。返回undefined。最终页面报错TypeError: Cannot read property 'Chart' of undefined

**Comment by wupeiwen** [comment]
我找时间在nuxt中试一试，之后给回复

**Comment by wupeiwen** [comment]
原因：
目前@antv/g2版本升级到了4.x，组件库是基于3.x版本封装的

解决办法：
将package.json中的依赖版本做如下修改
![微信截图_20200509140823](https://user-images.githubusercontent.com/11923878/81465769-f23c9a00-91fe-11ea-8147-ad9d32f30638.png)

验证结果截图：
![微信截图_20200509140809](https://user-images.githubusercontent.com/11923878/81465773-041e3d00-91ff-11ea-8348-9ca6032dcdbf.png)

**Comment by kamhung** [comment]
好的，谢谢
