### ISSUE TITLE
如何动态加载数据?

### ISSUE THREAD

**Issue by patwangx** [wupeiwen/vue-g2#42]
请问如何动态加载数据?

直接修改绑定的data，好像不起作用。
强制使用drawChart方法，可以重新加载数据，但chart配置有所异常
如果再载入一次好像又正常了。

**Comment by wupeiwen** [comment]
![代码截图](https://user-images.githubusercontent.com/11923878/82403102-9f7da080-9a90-11ea-93e9-4d554c91cf5f.jpg)
试试看 @patwangx

**Comment by Vbubblery** [comment]
没有用，并没有重新渲染。

**Comment by wupeiwen** [comment]
@Vbubblery @patwangx 抱歉，上次疏忽了该问题。缺陷原因:2.0.2版本重构测试过程中注释了部分代码，引发了该问题。已经推送2.0.4版本，更新可解决该问题。
